# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GALTASHMA | DONT NIBBLE, JUST BYTE
email: gtappsdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Personal blog where I will be writing whats on my mind. Currently based on Jekyll + Github.
    My Hobbies mostly include programming, arts, design and electronics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.galtashma.com/" # the base hostname & protocol for your site
# url: "http://bitterbit-github-io-galtashma.c9users.io/" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
twitter_username: galtashma
github_username: bitterbit 

# Build settings
markdown: kramdown
